[lint]
select = ["ALL"]

ignore = [
	"D200", # One-line docstring should fit on one line,
	"D212", # Multi-line docstring summary should start at the first line
	"COM812", # Trailing comma missing
]

[lint.per-file-ignores]
"__init__.py" = ["D"]
