[lint]
select = ["ALL"]

ignore = [
	"DJ", # Django
	"D200", # One-line docstring should fit on one line,
	"D212", # Multi-line docstring summary should start at the first line
	"COM812", # Trailing comma missing
	"ERA001", # Found commented-out code
	"S101", # Use of `assert` detected, This is disabled because pytest uses assert statements
]

[lint.per-file-ignores]
"__init__.py" = ["D"]
