# Generated by Django 5.1.3 on 2024-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('groups', '0003_alter_group_currency_groupmember_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='associated_categories', to='categories.category'),
        ),
    ]
