# Generated by Django 5.1.3 on 2024-12-18 17:19

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('currency', '0001_initial'),
        ('groups', '0004_group_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('created_by'), name='unique_group_title_per_user_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_group_member'),
        ),
    ]
