name: Django CI

# Trigger on pull requests to the main branch
on:
  pull_request:
    branches: ["main"]

# Define the jobs to run
jobs:
  # Run the tests
  test:
    # Run on the latest Ubuntu version
    runs-on: ubuntu-latest

    # Define the steps to run
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          pytest src/
